name: hello-blog

services:
  mongodb:
    image: mongo:7.0.14
    container_name: hb-database
    command: mongod --replSet rs0
    ports:
      - "27117:27017"
    networks:
      - hb-network
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s
    volumes:
      - hb_database_data:/data/db
      - hb_database_logs:/data/logs

networks:
  hb-network:

volumes:
  hb_database_data:
  hb_database_logs:
  hb_frontend_logs:
  hb_backend_logs:
