FROM rust:1 AS build-env
WORKDIR /app
COPY backend /app/backend
COPY frontend /app/frontend
COPY Cargo.toml /app/Cargo.toml
COPY Cargo.lock /app/Cargo.lock

RUN cargo build -p backend --release

FROM gcr.io/distroless/cc-debian12
COPY --from=build-env /app/target/release/backend /
CMD ["./backend"]