# --- FE BUILDER IMAGE --- #

FROM rust:slim-bookworm AS frontend-builder

WORKDIR /app

# Install required components
RUN rustup target add wasm32-unknown-unknown
RUN cargo install --locked trunk

# Copy files and install rust components
COPY ./frontend .
RUN cargo build

# Build the application
RUN trunk build --release


# --- BE BUILDER IMAGE --- #

FROM rust:1 AS backend-builder
WORKDIR /app
COPY backend /app/backend
COPY Cargo.toml /app/Cargo.toml
COPY Cargo.lock /app/Cargo.lock

RUN cargo build --release

# --- SERVING IMAGE --- #

FROM gcr.io/distroless/cc-debian12
COPY --from=frontend-builder /app/dist/ /frontend-files
COPY --from=backend-builder /app/target/release/backend /
ENV FRONTEND_MODE="integrated:frontend-files"
CMD ["./backend"]
